### ISSUE TITLE
Example is not working

### ISSUE THREAD

**Issue by philicious** [CircleCI-Public/gcp-gcr-orb#9]
### What happened
When using the example from this orb (and https://circleci.com/orbs/registry/orb/circleci/gcp-gcr) , you get 
> Cannot find a definition for job named gcp-gcr/build_and_push_image_using_remote_docker

This is because the job is actually named `build_and_push_image` as seen here https://github.com/CircleCI-Public/gcp-gcr-orb/blob/master/src/%40orb.yml#L126

### Expected behavior

Example being correct and working

**Comment by felicianotech** [comment]
Good catch. Getting this fixed.

**Comment by philicious** [comment]
only saw it now: this was also fixed in #2 (which can now be closed)

**Comment by lpzdvd-packlink** [comment]
Hi everyone,

It's still failing for me using 0.3.0 and this *config.yml*

```yaml
version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.3.0
workflows:
  build_and_push_image:
    jobs:
      - gcp-gcr/build_and_push_image
          image: my-image
          registry-url: eu.gcr.io
```

Build error:

```bash
#!/bin/sh -eo pipefail
# Error calling workflow: 'build_and_push_image'
# Cannot find a definition for job named gcp-gcr/build_and_push_image
# 
# -------
# Warning: This configuration was auto-generated to show you the message above.
# Don't rerun this job. Rerunning will have no effect.
false
Exited with code 1
```

**Comment by lpzdvd-packlink** [comment]
Changed to *build-and-push-image* works (use '-' instead of '_')
